/*

 KEYBOARD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : font.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define gl_keyboardWidth 20
#define gl_keyboardHeight 18
#define gl_keyboardBank 0

extern unsigned char gl_keyboard[];

/* End of KEYBOARD.H */
